name: Project automations
on:
    issues:
        types:
            - opened
            - reopened
    pull_request:
        types:
            - opened
            - reopened
            - review_requested
            - closed

env:
    todo: Todo
    done: Done
    in_progress: In Progress

jobs:
    issue_opened_or_reopened:
        name: issue_opened_or_reopened
        runs-on: ubuntu-latest
        if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
        steps:
            - name: Move issue to ${{ env.todo }}
              uses: leonsteinhaeuser/project-beta-automations@v1.1.1
              with:
                  gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
                  organization: owid
                  project_id: 4
                  resource_node_id: ${{ github.event.issue.node_id }}
                  status_value: ${{ env.todo }} # Target status
            - name: Label issues
              uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
              with:
                  add-labels: "needs triage"
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue_closed:
        name: issue_closed
        runs-on: ubuntu-latest
        if: github.event_name == 'issues' && github.event.action == 'closed'
        steps:
            - name: Moved issue to ${{ env.done }}
              uses: leonsteinhaeuser/project-beta-automations@v1.1.1
              with:
                  gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
                  organization: owid
                  project_id: 4
                  resource_node_id: ${{ github.event.issue.node_id }}
                  status_value: ${{ env.done }} # Target status
    pr_opened_or_reopened_or_reviewrequested:
        name: pr_opened_or_reopened_or_reviewrequested
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'review_requested')
        steps:
            - name: Move PR to ${{ env.in_progress }}
              uses: leonsteinhaeuser/project-beta-automations@v1.1.1
              with:
                  gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
                  organization: owid
                  project_id: 4
                  resource_node_id: ${{ github.event.pull_request.node_id }}
                  status_value: ${{ env.in_progress }} # Target status
    pr_closed:
        name: pr_closed
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        steps:
            - name: Move PR to ${{ env.done }}
              uses: leonsteinhaeuser/project-beta-automations@v1.1.1
              with:
                  gh_token: ${{ secrets.PROJECT_ISSUES_TOKEN }}
                  organization: owid
                  project_id: 4
                  resource_node_id: ${{ github.event.pull_request.node_id }}
                  status_value: ${{ env.done }} # Target status
