name: Auto-deploy to GitHub Pages

# Builds and deploys Storybook and a Jest coverage report to owid.github.io.
# Most stuff in here is handled by https://github.com/marketplace/actions/deploy-to-github-pages

on:
    push:
        branches:
            - master
jobs:
    build-deploy-storybook-coverage:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - uses: ./.github/actions/setup-node-yarn-deps
            - uses: ./.github/actions/build-tsc

            # Note: running these two build steps subsequently means that if either `buildStorybook` or `coverage` fails,
            # neither of them is deployed :(
            # Let's hope this doesn't happen too often

            - name: Build Storybook üîß
              run: yarn buildStorybook

            - name: Generate Jest coverage report üÉè
              run: yarn buildCoverage

            - name: Generate coverage badge üîñ
              run: |
                  mkdir -p badges
                  yarn add lcov-badge@1.0.4
                  yarn lcov-badge -o badges/coverage.svg coverage/lcov.info

            # We're using two subsequent deploys instead of making them parallel because `github-pages-deploy-action`
            # force-pushes, and if we have two deploys running at the same time that might lead to missing update situations.

            - name: Deploy Storybook üöÄ
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.STORYBOOK_DEPLOY_ACCESS_TOKEN }}
                  branch: master
                  folder: .storybook/build
                  repository-name: owid/owid.github.io
                  target-folder: stories
                  commit-message: |-
                      ü§ñ update Storybook
                      owid/owid-grapher@${{ github.sha }}
                  git-config-name: owidbot
                  git-config-email: tech@ourworldindata.org

            - name: Deploy Coverage Report üöÄ
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.STORYBOOK_DEPLOY_ACCESS_TOKEN }}
                  branch: master
                  folder: coverage/lcov-report
                  repository-name: owid/owid.github.io
                  target-folder: coverage
                  commit-message: |-
                      ü§ñ update coverage report
                      owid/owid-grapher@${{ github.sha }}
                  git-config-name: owidbot
                  git-config-email: tech@ourworldindata.org

            - name: Deploy Badges üöÄ
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  token: ${{ secrets.STORYBOOK_DEPLOY_ACCESS_TOKEN }}
                  branch: master
                  folder: badges
                  repository-name: owid/owid.github.io
                  target-folder: badges
                  commit-message: |-
                      ü§ñ update badges
                      owid/owid-grapher@${{ github.sha }}
                  git-config-name: owidbot
                  git-config-email: tech@ourworldindata.org
