name: Upload to R2
on:
    push:
        branches:
            - master
        paths:
            - "packages/@ourworldindata/grapher/src/schema/**"
    workflow_dispatch:

jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@master

            - uses: ./.github/actions/setup-node-yarn-deps

            - uses: hustcer/setup-nu@v3
              with:
                  version: "0.101" # Don't use 0.101 here, as it was a float number and will be convert to 0.101, you can use v0.101/0.101.0 or '0.101'
            # Turn all yaml files in the schema directory into json (should only be one)
            - run: |
                  (ls packages/@ourworldindata/grapher/src/schema/*.yaml
                  | each {|yaml|
                      open $yaml.name
                      | to json
                      | save -f ($yaml.name
                          | path parse
                          | upsert extension "json"
                          | path join) })
              shell: nu {0}
            # Construct default config objects for all grapher schemas in the schema directory (should only be one)
            - run: |
                  (ls packages/@ourworldindata/grapher/src/schema/grapher-schema.*.json
                  | each {|json|
                      yarn tsx --tsconfig tsconfig.tsx.json devTools/schema/generate-default-object-from-schema.ts $json.name
                      | save -f ($json.name
                          | path parse
                          | upsert stem ($json.name
                              | path parse
                              | get stem
                              | str replace 'grapher-schema' 'grapher-schema.default')
                          | path join) })
              shell: nu {0}
            # Get all files in the schema directory that end with digits.json or digits.yaml and
            # copy them to a file called .latest.json or .latest.yaml
            - run: |
                  ( ls packages/@ourworldindata/grapher/src/schema/*
                     | where name =~ '\d+.(json|yaml)$'
                     | get name
                     | each { |it| cp $it ($it | str replace -r '\d+.(json|yaml)$' 'latest.$1') })
              shell: nu {0}
            - run: ls packages/@ourworldindata/grapher/src/schema
              shell: nu {0}
            # Now upload all files in that folder to Cloudflare R2.
            - name: Configure R2 credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
                  aws-region: auto

            - name: Upload to R2
              run: |
                  aws s3 sync packages/@ourworldindata/grapher/src/schema s3://owid-public/schemas \
                    --endpoint-url https://${{ secrets.CLOUDFLARE_R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
